# Generated by Django 5.0.4 on 2024-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedcontent",
            name="key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
