# Generated by Django 5.0.4 on 2024-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_encryptedcontent_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedcontent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="encryptedcontent",
            name="key",
        ),
        migrations.AlterField(
            model_name="encryptedcontent",
            name="content_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="encryptedcontent",
            name="unique_identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
